version: "3"
services:
  client:
    image: earlp3/multi-client
    mem_limit: 128m
    hostname: client
  express:
    image: earlp3/multi-server
    mem_limit: 128m
    hostname: express
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: earlp3/multi-worker
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: earlp3/multi-nginx
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
