branch-defaults:
  main:
    environment: Multi-docker-env
environment-defaults:
  Multi-docker-env:
    branch: null
    repository: null
global:
  application_name: multi-docker
  default_ec2_keyname: null
  default_platform: Docker running on 64bit Amazon Linux 2023
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
