version: "3"
services:
  # server: express
  server:
    build:
      dockerfile: Dockerfile.dev
      context: .
    port:
      - "5000:5000"
    volume:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
  redis:
    image: "redis:latest"
    environment:
      -
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=postgres_password
